before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: Qvjik0Km+UNFrLq8RDC49fFCSTnRDef56uHDX81YVCuTZJVE3o4MPHDmTRZdyCwD2WWSovZbjHOiJLFD3y8KIpOwnOvFAAUGjLq5DbicnVKJ5JW/3++VZPp/xGMvqmD+Homu2Vty5QEOL14OA47bos3veW/v/0jyxC1LKTpzt54= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YzlhMmRlM2ZmNmVmMmJlMTU1ZWI3ZWJhNjc3ZDhjOGM=jDPDHyJJB570nNyec32k9dG4HrrffNtTzI4yLzIGvhqvVq/dHuTXESz/ioXS2YASPTB0hsKZmCTr5HF2RGq0G77Rq3iNP4ABCEbjl6vJ0w1JRrr/kKSXEqmpVohhxLI9An1mK3rEV6IQOQzuiTZJZO75TcEltMI7NcBp/7A+a52+d+G9gDFwrrponUyq07fqqHDUImO9+Y4FWLqf6Pz/v8LJR9RIhY56Dbv9ZTuYqWl8z1t6LZqH0xsbdM3kpsZ+7g3l9tYYi0JRxrTZcJCLQ4box7Qq/3TtNzc9gwgozEUdFxbYDpZUI1ZZWAqGulKNrtJy5Ie+gzk92KZp8V7QV6fCkn4Xr9QqZjkpHAcWowWscHhhsLGV3Ec1BF0AK+b4YDKkEjDO6/Qz7jOPyNvVRV8l1TtIZlA/0EDfMNO5IrmVnDNgramVXvYAez3JJpnze/kxXj9qHQJp/ukCnddtkpL37e8BCHtskCg6+E81ALVuKSSt+BGSYm2TLSOiJVlydEkem75n0AaSDs2ySdWCVekQoK98FtIGJZYWE3b0QZezYdJgGL+8J8PsNOYdqouzsk3wJDVlPev+9Qz+DbIPAqWkv84tPNW11TnP7gF9/Q4QWa0Nq+g73PrhckME7NZFOIpe+gevN9nmcIHGY4888HahMFIm/tKAgGyEbkZW3EW1A7ohxsxPYpYJgwVD2Z8heu0USTaGssgPVS8sfzT+lwoXlErxycQSZsYWz+ZuNDupukan9DUK3gfYCRdTmfopW0w4Z1eJVHkVTZTTnfJEejKZxl34BBYi00cO1J0+1mJ9FV0pvWTQQDYX/7C8j/46ajyyGgUg5XK5BmJg2cOM4ge8yT1liDAFT44D78nzm2lzKzW3PEnm3ApFAVzm3yCGuUUv/pc2Mx84jqMe3PGmLVbuIDShyGDL5oLhivgmXmkLyAOxrJBvZ/VBAilL+KFqYdokj94wI8IvJrt1jhy6qmzkJqYItc150P6BuE52QHQDYpdZ+rJsSe30YMDPjyiRfVQQfu8gV7uaTU05X4MJBVVsn0rnV7KmPKkRypL0MrScfcidgUd/RHbeyMiFOUBpvFBXiyO9cCa1C8USNFXuFrlXo2MFkc8cQjfh/BB/zjQaHLUYMbhGwVqOmbxCmc7UqS545HrJYsyLZXI3xxu2F71118jCEWqao/R/LNp0dwH4/LbdrtuyWTNv70NfJSfbGGvK0KIca9RqFj0Si+y1nOt8YRgk7TapQfuUBWJi9MuyGvAu1KcUT2hLSEHeHqDEruReezt78HuLJWLT8Wuh0hLRpYoLaXlQ15f6qsjOwd0= # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
