before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: HM0LyEUlQ1K57/H2Y3CQC693qAgGIB1/1jmYMjVAusiw5luTz16ExigxqRcr0eGzQUm1Vhahlaa19qrtXSFmGbrX7KYQhyLSn1m1grhtDlv1AvIjVx1qk7f5GagPKv/mq3Hj4B6+wQr86pmRvYPOUjsNb1BrXx7JiYbDa//Oc2E= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: Y2Q2MjZkN2FhOTg4ZGYxNmY0NmY1NWZjODljNDhmOTA=u+criHtuROXe21w1IG7ChfTOiQPW2UAU4lPkGaFNrC6xlIleFcbJHvWBgrfMbCeb/LApQ/nSWjAwUmzlQy1PMmcqm0bhM5To/tcYDzHflSX+NiVzJC2A6GTIHVK6Qsp5cwulVvQV50WBWixdlX4Ndzl/7KaCigszDPOXCDAqjpxJqoi1GcL90lvMgNCFVye9+imbm1Ax9vZaVcLzqyv+52RK2FLq8F1TQ/9+5q6npjN4UvGwUKGIaNqewCFWahCsekomXWqm+lZqYXlvloM8csnck0tg6+ITv1Z6TOgJhiZQoFNcQfiSEwB4fJH6LAcfS6qAjgbtOnKbDeNda4AFhUqs58TycrVU9GC4BU5OJBg/kHoDa5LSOOdLff0YuDtplB/yK5S533/gpn3FLi1JlP6GoeepytVMN20DGDvpsggiE+PC1l4viVNKWu/Pv5r9B+S0bCKpRrPpgJ5VcGR6VPG99G2PKcluQXm3E/2j7yeBj5167S+2b5zOYi7zISTTyzcBCXiqierlxBQ/7+A48MpCx9pUlQ/ZAGL2it6OLlO3wRZomLssi71yK2KvttAPobGgc9g1wQNPA0jXnnCDC+Z0b8gIO7pCzVfBA7hmUkSsKXe4ZSBILp9J3e7upDNCc5V3AHTbZ/y8TUz7PvSbROSbz+z10qdSgvs+gSIdGgE4Y2eIo3B1S7UZXGesqzq7WVHnJYTs191EsfkXcEj9AQsunYeK1jRHe5s7G3knS/Cer2j+4AB3azg/7dl8IB13zJPlM7J3+LoLfATuRLSRLiXjkKp2ySNimao3ZiamATHYA/Eub8DkO07YPe9wFHVifBDW1wcNY5SPTFrDV7a0ndJR2nu+AU93AxX9JkvHyxc3ow1xeGKUmc93R+tzPhM3mHsPWkRmepHlWMaJLkGWEsrLFkxJYrl2+agG2chP/ZBh+vWUvqMG5eoePx9AHGF40B1pEQScjxYm6Ol9k1tAwVrsBQLs+YvL6435Twd8HafS/qwE+ZZQHNITENdOZxhsaGGRBAt078hYd/7KuwVaig== # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
